### ISSUE TITLE
Adding a DESTROY method

### ISSUE THREAD

**Issue by nigelm** [nupfel/Web-API#26]
I am using a Moose app which uses `Mail::Chimp3` (based on Moo) which consumes `Web::API`

Each time the app completes I get an error thrown:-

    Web::API: ERROR: unknown command: DESTROY

I suspect something in this chain of differing object systems is forcing a full object tear down calling the `DESTROY` method on the components, which hits your `AUTOLOAD`.

Would it be possible to add an explicit `DESTROY` method or a specific catch for it in the `AUTOLOAD`?

**Comment by nupfel** [comment]
oh yea, no problem at all :)

**Comment by nupfel** [comment]
the new version 2.2.1 should be up on PAUSE within the next few hours
