### ISSUE TITLE
decreasing versions

### ISSUE THREAD

**Issue by chorny** [nupfel/Web-API#27]
Versions with 2 dots are converted to real numbers. 0.1.1 means 0.001001. So 0.1 > 0.1.1.
Versions with one dot are real numbers. So 0.9 > 0.10.
Best is to delete distributions that have bigger versions that latest or just any old versions (that will help new installations). And upload new distribution with correct version (that will help users that have older version installed).

You can check this using version->parse:

perl -Mversion -E"say version->parse('1.1')->normal"
v1.100.0

perl -Mversion -E"say version->parse('1.1.1')->normal"
v1.1.1

perl -Mversion -E"say version->parse('1.1') <=> version->parse('1.1.1')"
1

It is recommended to increase major version when switching between one dot and two dot schemes.

**Comment by nupfel** [comment]
yea i learned that the hard way :)
thanks for explaining!
i swapped to a 2 dots version now and this thursday the versioning should work properly again on CPAN/PAUSE once the older ones are deleted.
