### ISSUE TITLE
suppress http errors from log if not in debug mode

### ISSUE THREAD

**Issue by yahermann** [nupfel/Web-API#30]
It's very common to expect an http error in the course of "normal" (non-erroneous) operation.  For example, we sometimes want to check if a resource exists, e.g. `GET /some_resource/:id`, and we expect to see an `http 404` error if it doesn't.  

We don't want to pollute the logs with this type of "normal" activity.  

Suggested mod, starting in line 807 (https://metacpan.org/release/Web-API/source/lib/Web/API.pm, version 2.6):

    if ($error) {
        chomp($error);
        $self->log("ERROR: $error");      #ADD:  if $self->debug;
        $answer->{error} = $error;
    }

**Comment by nupfel** [comment]
hi @yahermann, thanks for your interest in this project and submitting an issue!

I agree and changed the behaviour as suggested in the next version
