### ISSUE TITLE
Smartmatch is deprecated in 5.30.0

### ISSUE THREAD

**Issue by mschout** [nupfel/Web-API#31]
As of perl 5.38.0 smartmatch is deprected.

Probably should remove all references to it.

```
given is deprecated at /vendor/local/lib/perl5/Web/API.pm line 376.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 377.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 383.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 384.
given is deprecated at /vendor/local/lib/perl5/Web/API.pm line 417.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 418.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 424.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 425.
given is deprecated at /vendor/local/lib/perl5/Web/API.pm line 450.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 451.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 452.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 456.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 466.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 472.
Smartmatch is deprecated at /vendor/local/lib/perl5/Web/API.pm line 722.
Smartmatch is deprecated at /vendor/local/lib/perl5/Web/API.pm line 919.
```

**Comment by nicklangridge-amtivo** [comment]
- https://github.com/nupfel/Web-API/pull/32

^ Although I appreciate the maintenance PR, unfortunately the change from @mschout broke support for any auth type other than 'basic'.

See the change at line https://github.com/nupfel/Web-API/compare/v2.7..v2.8#diff-6300bb396beff93cfbe585c0df70ceb44eb11363d885c04d3d4f28da2ebb2a41R862

```
if ('basic') ...
```
This will always be true. Instead the condition should use a regex like:
```
if (/^basic$/) ...
```

Some of the `elseif()` conditions have the some problem and should also be replaced with a regex.

**Comment by nupfel** [comment]
my bad! I have to admit that I have not been using this module anymore for a very long time. In fact I don´t even use much Perl in general anymore. Thank you very much for the MR that solved the issue finally!

**Comment by nicklangridge-amtivo** [comment]
Many thanks!
